version: '3'

services:
    client:
        container_name: contact_manager_frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - './frontend:/app'
            - '/app/node_modules'
        ports:
            - 3000:3000
        env_file:
            - './.env'
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        networks:
            - localnet
    server:
        container_name: contact_manager_backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        command: npm run server
        ports:
            - '5000:5000'
        volumes:
            - './backend:/usr/src/app'
        env_file:
            - './.env'
        networks:
            - localnet
        links:
            - mongo
    mongo:
        image: mongo
        container_name: contact_manager_db
        ports:
            - '27017:27017'
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        networks:
            - localnet
    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
        depends_on:
            - mongo
        networks:
            - localnet
volumes:
    node_modules:
    web-root:
        driver: local
networks:
    localnet:
        driver: 'bridge'
